# Site settings
title: Work of Calvin Doval
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A website of the designs, developments, rambling and other fun things of Calvin Doval.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cydoval.com" # the base hostname & protocol for your site
twitter_username: cydoval
github_username:  cydoval

# Build settings
markdown: kramdown
