# Site settings
title: The work and thoughts of Calvin Doval
description: > # this means to ignore newlines until "baseurl:"
  The work of Calvin Doval
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cydoval.com" # the base hostname & protocol for your site
twitter_username: cydoval
github_username:  cydoval


paginate: 3
# Build settings
markdown: kramdown
